resources:
- name: google-auth
  type: solutions.api
  properties:
    inputs:
    - name: org
      prompt: Edge Org name
    - name: username
      prompt: Username
      ifNotPresent: token
    - name: password
      prompt: Password
      hidden: true
      ifNotPresent: token
    - name: env
      prompt: Edge Org Environment
    - name: projectId
      prompt: GCP Project Id
    - name: privateKey
      prompt: Service account private Key
    - name: serviceAccountEmail
      prompt: Service account email

    configurations:
    - env: test
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      sms_endpoint: https://rest.nexmo.com/sms/json

    - env : prod
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      sms_endpoint: https://rest.nexmo.com/sms/json

    edgeOrg:
    script: gulpfile.js
    basePath: .
    subResources:
    #- name: message_kvm
    #  type: kvm
    #  items:
    #  - name: BankKVM
    #    payload: '{ "name" : "ServiceAccountEntries", "entry" : [ { "name" : "privateKey", "value" : "{{privateKey}}" } ] , "encrypted": "true"}'
    - name: cacheResources
      type: cache
      items:
      - name: access-token
        payload: '{ "name": "access-token"}'
    - name: replaceorgvalues
      type: configSubstitutions
      items:
      - name: projectId
        filePaths: ['src/gateway/google-auth/target/apiproxy/resources/node/config.json']
        value: '{{ projectId }}'
      - name: privateKey
        filePaths: ['src/gateway/google-auth/target/apiproxy/resources/node/config.json']
        value: '{{ privateKey }}'
      - name: serviceAccountEmail
        filePaths: ['src/gateway/google-auth/target/apiproxy/resources/node/config.json']
        value: '{{ serviceAccountEmail }}'

    - name: apis
      type: proxy
      items:
      - name: google-auth
        apiName: google-auth
